apiVersion: v1
data:
  policy.csv: |
    p, role:devops, *, *, *, allow
    p, role:devops, *, *, */*, allow
    p, role:devops, exec, create, */*, allow
    p, role:developer, applications, get, */*, allow
    p, role:token, applications, sync, */*, allow
    p, role:token, applications, get, */*, allow
    p, role:token, repositories, get, *, allow
    g, varun, role:devops
    g, sagar, role:developer
    g, citoken, role:token
  policy.default: ""
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"p, role:devops, *, *, *, allow\np, role:devops, *, *, */*, allow\np, role:devops, exec, create, */*, allow\np, role:developer, applications, get, */*, allow\np, role:token, applications, sync, */*, allow\np, role:token, applications, get, */*, allow\np, role:token, repositories, get, *, allow\ng, varun, role:devops\ng, sagar, role:developer\ng, citoken, role:token\n","policy.default":"","scopes":"[groups]"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"argocd","meta.helm.sh/release-namespace":"argocd"},"creationTimestamp":"2023-09-25T11:12:26Z","labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd","app.kubernetes.io/version":"v2.8.4","helm.sh/chart":"argo-cd-5.46.7"},"name":"argocd-rbac-cm","namespace":"argocd","resourceVersion":"76002","uid":"1e16fa11-d45d-4ea5-9765-43bf476e1bbb"}}
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-10-09T15:10:25Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.8.4
    helm.sh/chart: argo-cd-5.46.7
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "329160"
  uid: b863c18e-b860-41b5-8713-1e2ade268bea
