apiVersion: v1
data:
  accounts.citoken: apiKey
  accounts.sagar: apiKey,login
  accounts.varun: apiKey,login
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"accounts.citoken":"apiKey","accounts.sagar":"apiKey,login","accounts.varun":"apiKey,login","configManagementPlugins":"- name: argocd-vault-plugin\n  generate:\n    command: [\"argocd-vault-plugin\"]\n    args: [\"generate\", \"./\"]"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-09-29T17:36:43Z","labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd","resourceVersion":"491","uid":"a0c3b0af-f6a6-4408-9243-a71cb33a1554"}}
  creationTimestamp: "2023-10-09T15:09:52Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "329115"
  uid: 6018c9a1-751a-4fb1-9ae9-6e0a36244753
